name: gs3
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pytorch=2.2.0
  - torchvision=0.17.0
  - torchaudio=2.2.0
  - pytorch-cuda=12.1
    #- cudatoolkit=12.1
  - plyfile=0.8.1
  - python=3.11
    # - pip=22.3.1
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
